# This action releases refnx on PyPI for every version tagged commit (e.g. v0.0.1)
name: PyPI/Github Release

on:
  push:
    tags:
      - "R*"


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_TEST_COMMAND: pytest --pyargs refnx.reflect.test.test_reflect
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="10.13"

      - uses: actions/upload-artifact@v3
        with:
          name: refnx-wheels
          path: ./wheelhouse/*.whl

  check-version:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build-wheels]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - uses: actions/download-artifact@v3
      with:
        name: refnx-wheels
        path: dist
    - name: Check version
      run: |
        python -m pip install --only-binary=refnx --no-index --find-links=. refnx

        RNX_VERSION="$(python -c "import refnx;print(refnx.version.release)")"
        if  [ $RNX_VERSION == "False" ]; then
          echo "It's a release version of refnx"
          else
            echo "This is not a release version of refnx"
            exit 1
        fi

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [check-version]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/refnx
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: refnx-wheels
        path: dist

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip_existing: true
