# This action releases refnx on PyPI for every version tagged commit (e.g. v0.0.1)
name: PyPI/Github Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        os: [windows-latest, macos-14]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: build wheels
        uses: pypa/cibuildwheel@ee63bf16da6cddfb925f542f2c7b59ad50e93969 # v2.22.0
        env:
          CIBW_TEST_COMMAND: pytest --pyargs refnx.reflect.test.test_reflect
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="10.13"

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl


  build_linux_x86_64_wheels:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: build wheels
        uses: pypa/cibuildwheel@ee63bf16da6cddfb925f542f2c7b59ad50e93969 # v2.22.0
        env:
          CIBW_TEST_COMMAND: pytest --pyargs refnx.reflect.test.test_reflect
          CIBW_BUILD: "*-manylinux_x86_64"

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: wheels-manylinux
          path: ./wheelhouse/*.whl


  build_linux_musl_wheels:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: build wheels
        uses: pypa/cibuildwheel@ee63bf16da6cddfb925f542f2c7b59ad50e93969 # v2.22.0
        env:
          CIBW_TEST_COMMAND: pytest --pyargs refnx.reflect.test.test_reflect
          CIBW_BUILD: "*-musllinux_x86_64"

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: wheels-musllinux
          path: ./wheelhouse/*.whl


  make_sdist:
    name: Make sdist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: wheels-sdist
        path: dist/*.tar.gz


  check-version:
    runs-on: ubuntu-latest
    needs: [build_linux_musl_wheels, build_linux_x86_64_wheels, build_wheels, make_sdist]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: 3.11
    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        pattern: wheels-*
        merge-multiple: true
        path: dist
    - name: Check version
      run: |
        python -m pip install numpy scipy orsopy
        ls dist
        python -m pip install --only-binary=refnx --no-index --find-links=dist refnx
        cd dist
        RNX_VERSION="$(python -c "import refnx;print(refnx.version.release)")"
        cd ..
        if  [ $RNX_VERSION == "True" ]; then
          echo "It's a release version of refnx"
          else
            echo "This is not a release version of refnx"
            exit 1
        fi


  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [check-version]
    environment:
      name: pypi
      url: https://pypi.org/p/refnx
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        pattern: wheels-*
        merge-multiple: true
        path: dist

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70 # v1.12.3
      with:
        # repository-url: https://test.pypi.org/legacy/
        skip_existing: true


  release-github:
    runs-on: ubuntu-latest
    needs: [ pypi-publish ]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        pattern: wheels-*
        merge-multiple: true
        path: dist

    - uses: ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87 # v1.15.0
      with:
        artifacts: "dist/refnx*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        generateReleaseNotes: true
